#This file is automatically generated; do not edit.
SOURCES = ../versionData.py ../docs/conf.py ../jongle.py ../jongle/__init__.py ../jongle/Ui_main.py ../jongle/opencv.py ../jongle/fonctions_base.py ../jongle/main.py ../jongle/svgwidget.py ../jongle/objetphysique.py ../jongle/matrix.py
TRANSLATIONS = fr.ts
